Task 7
EDovgalo/moves pull request #5
Opened 2020-09-25 18:13 UTC by EDovgalo

2020-09-27 18:50 UTC, sulemanof commented on src/components/shared/modal/movieModal/MovieModal.tsx
> +window.moment = moment;
what is that?!?!?   😄

2020-09-27 18:55 UTC, sulemanof commented on src/components/shared/modal/deleteMovieModal/DeleteMovieModal.tsx
> +export const DeleteMovieModal = ({ onClose, onConfirm }: Props): JSX.Element => (
Deleting of an item is not handled correctly:

![image](https://user-images.githubusercontent.com/31325372/94373156-337d0a00-010c-11eb-8057-0f0512ca15bf.png)

2020-09-27 18:58 UTC, sulemanof commented on src/components/shared/modal/deleteMovieModal/DeleteMovieModal.tsx
> +export const DeleteMovieModal = ({ onClose, onConfirm }: Props): JSX.Element => (
The same issue when editing an item

2020-09-27 18:59 UTC, sulemanof requested changes
Good usage of formik.
Please, update the app with the comments

2020-09-29 18:14 UTC, EDovgalo commented
> Good usage of formik.
> Please, update the app with the comments



> Good usage of formik.
> Please, update the app with the comments



> Good usage of formik.
> Please, update the app with the comments

Done

2020-09-29 18:15 UTC, EDovgalo commented
> Good usage of formik.
> Please, update the app with the comments

Done

2020-10-03 09:41 UTC, sulemanof commented on src/store/movies/actions.ts
> +  const queryParams = `?search=${search}`;
The search is still not working! You should specify the `searchBy` query param to achieve the result:
```
http://localhost:4000/movies?search=harry&searchBy=title
```

If you don't specify this param, api returns basic data

2020-10-03 09:51 UTC, sulemanof commented on src/components/toaster/ToasterNotification.tsx
> +  const currentMessages = useRef(messages);
I don't see a necessity in ref here.
You could just reach the result with `messages` state value.
And simplify the component code significantly

2020-10-03 09:53 UTC, sulemanof commented on src/components/hoc/withModals.tsx
>    };
wrapping these callbacks with `useCallback` would increse performance since you always pass these callbacks into child components and make them to re-render each time

2020-10-03 09:54 UTC, sulemanof commented on .eslintrc.json
> +    "plugin:react-hooks/recommended"
Thanks for adding this 👍

2020-10-03 09:55 UTC, sulemanof approved these changes
Ready for merge,
the app could be updated with all the comments in the next PR

2020-10-03 09:55 UTC, merged

2020-10-03 19:12 UTC, EDovgalo commented on src/components/hoc/withModals.tsx
>    };
fixed in next task

2020-10-03 19:27 UTC, EDovgalo commented on src/components/toaster/ToasterNotification.tsx
> +  const currentMessages = useRef(messages);
Can we discuss it ?